### PR TITLE
react scripts breaking change update

### PR DESCRIPTION
**Pull request by asparamancer**
currently if you download the repo and do `npm install` & `npm start` you'll get `TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined` 

bumping the version from 3.3.1 to 3.4.1 resolves it. 

cf. https://github.com/facebook/create-react-app/issues/8499
https://stackoverflow.com/a/60242323/3532661

### CODE REVIEW

**Comment by einazare** [comment]
Hello there, @asparamancer ,

Thank you for your PR, please point it to our dev-master branch, and we'll add it there.

Best,
Manu

**Comment by asparamancer** [comment]
Ok, done

**Comment by einazare** [comment]
Hello again, @asparamancer ,

Please revert the changes done to the following file: .github/workflows/main.yml

Best,
Manu

**Comment by asparamancer** [comment]
ok, done

**Pull request merged**
